site_name: Study Notes
theme: readthedocs

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math:
          enable_dollar_delimiter: True # enable $...$ for inline math

nav:
    - Introduction: "index.md"
    - Algorithm:
          - Alg blog: "algorithm/alg_blog_note.md"
          - Algorithms (4th Edition): "algorithm/algorithms_4th_edition.md"
    - Blockchain:
          - Blockchain: "blockchain/blockchain.md"
    - Deep Learning:
          - Google ML Crash Course: "deep_learning/google-machine-learning-crash-course.md"
          - Python机器学习: "deep_learning/Python机器学习.md"
          - Dive into Deep Learning: "deep_learning/dive_into_deep_learning.md"
          - DL Notes: "deep_learning/dl_notes.md"
    - Mathematics:
          - 数学之美: "mathematics/beauty_of_mathematics.md"
          - 统计学的世界: "mathematics/statistics_concepts_and_controversies.md"
    - Network:
          - 图解网络: "network/图解网络.md"
    - Psychology & Mind:
          - 与众不同的心理学: "psychology/与众不同的心理学.md"
          - 决策与判断: "psychology/决策与判断.md"
          - 暗时间: "psychology/暗时间.md"
          - 你的灯亮着吗: "psychology/你的灯亮着吗.md"
          - 沟通的艺术: "psychology/沟通的艺术.md"
          - 影响力: "psychology/影响力.md"
          - 专注力: "psychology/专注力.md"
    - Python:
          - pythonic: "python/pythonic.md"
          - python tips: "python/python_tips.md"
          - python3: "python/python3.md"
          - Effective Python: "python/effective_python.md"
          - Data Structures and Algorithms in Python: "python/data_structure_and_algorithms_in_python.md"
          # - Python Cookbook (143/2058): 'python/python_cookbook.md'
          # - Core Python Programming (2/662): 'python/core_python_programming.md'
          # - Fluent Python (42/1022): 'python/fluent_python.md'
          # - numpy: 'python/numpy.md'
    - Research:
          - 像外行一样思考，像专家一样实践: "research/像外行一样思考，像专家一样实践.md"
    - Startup:
          - How Google Works: "startup/how_google_works.md"
          - startup: "startup/startup.md"
    - Tools:
          - Arch Linux: "tools/arch.md"
          - Neovim: "tools/neovim.md"
          - Vim: "tools/practical_vim.md"
          - Shell: "tools/shell.md"
          - Git: "tools/git.md"
          - Docker (TODO): "tools/docker.md"
          - Makefile: "tools/makefile.md"
          - Markdown: "tools/markdown.md"
          # - org-mode: "tools/org-mode.org"
    - Other:
          - 编码 隐匿在计算机软硬件背后的语言: "other/code.md"
          - 上帝掷骰子吗？量子物理史话: "other/history_of_quantum_physics.md"
          - 高效能人士的7个习惯: "other/高效能人士的7个习惯.md"
          - 底层逻辑: "other/底层逻辑.md"
          - 高效程序员的45个习惯: "other/高效程序员的45个习惯.md"
          - Type System: "other/type_system.md"
    - Todo:
          - TODO: "todo/todo.md"
