site_name: Study Notes
theme: readthedocs

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
  - mdx_math:
      enable_dollar_delimiter: True # enable $...$ for inline math

nav:
  - Introduction: "index.md"
  - AI:
      - Dive into Deep Learning: "AI/d2l.md"
  - Mathematics:
      - 数学之美: "mathematics/beauty_of_mathematics.md"
      - 统计学的世界: "mathematics/statistics_concepts_and_controversies.md"
  - Network:
      - 图解网络: "network/图解网络.md"
  - Psychology & Mind:
      - 蛤蟆先生去看心理医生: "psychology/蛤蟆先生去看心理医生.md"
      - 与众不同的心理学: "psychology/与众不同的心理学.md"
      - 决策与判断: "psychology/决策与判断.md"
      - 暗时间: "psychology/暗时间.md"
      - 你的灯亮着吗: "psychology/你的灯亮着吗.md"
      - 沟通的艺术: "psychology/沟通的艺术.md"
      - 影响力: "psychology/影响力.md"
      - 专注力: "psychology/专注力.md"
  - Startup:
      - How Google Works: "startup/how_google_works.md"
      - YC startup course: "startup/how_to_start_a_startup.md"
  - Tools:
      - arch linux: "tools/archlinux.md"
      - bash: "tools/bash.md"
      - vim: "tools/practical_vim.md"
      - neovim: "tools/neovim.md"
      - git: "tools/git.md"
      - docker: "tools/docker.md"
      - python3: "python/python3.md"
      - pythonic: "python/pythonic.md"
  - Other:
      - 像外行一样思考，像专家一样实践: "research/像外行一样思考，像专家一样实践.md"
      - 上帝掷骰子吗？量子物理史话: "other/history_of_quantum_physics.md"
      - 高效能人士的7个习惯: "other/高效能人士的7个习惯.md"
      - 底层逻辑: "other/底层逻辑.md"
      - 高效程序员的45个习惯: "other/高效程序员的45个习惯.md"
      - Type System: "other/type_system.md"
      - Principles: "other/principles.md"
  - Todo:
      - TODO: "todo/readling_list.md"
